name = "email-sender-worker"
main = "index.ts"
compatibility_date = "2023-10-02"

routes = [
	{ pattern = "email-worker.study-llm.me", custom_domain = true }
]

[triggers]
crons = ["0 8 * * *"]

[[kv_namespaces]]
binding = "EMAIL_JOBS"
id = "ee95c68527e74031a4af461974e7f1b8"
preview_id = "ee95c68527e74031a4af461974e7f1b8"
